disabled_rules: # This rules will be ignored
  - empty_enum_arguments
  - leading_whitespace
  - unused_optional_binding
  - trailing_whitespace
  - todo
  - xctfail_message

opt_in_rules: # This optional rules will be enforced
  - empty_count
  - weak_delegate
  - unused_capture_list
  - closure_body_length
  - force_unwrapping
  - force_cast
  - force_try
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - private_swiftui_state
  - return_value_from_void_function
  - unowned_variable_capture

excluded:
  - dependencies
  - "Tuist/Dependencies/*"
  - fastlane
  - Plugins
  - Resources
  - "Tuist/ProjectDescriptionHelpers"
  
line_length:
  warning: 200
  error: 250

# Configurable rules
type_name:
  min_length:
    error: 3
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL

identifier_name:
  allowed_symbols: "_"
  
reporter: "xcode"